### ISSUE TITLE
Unable to set files or folders as private

### ISSUE THREAD

**Issue by vaz-ar** [cozy/cozy-files#260] opened 2015-04-01 10:43 UTC
Version  1.1.4 

Every time I try to set a file or folder as private and save, it still appears as shared the next time I open the "share" pop up.

**Comment by jsilvestre** [comment] 2015-05-05 08:24
Apparently it's not a bug, it's a feature: https://github.com/cozy/cozy-files/blob/master/client/app/views/modal_share.coffee#L28

I'm going to talk with the team so we can improve the experience.

**Comment by jsilvestre** [comment] 2015-05-05 12:09
So we won't change this, I'm closing the issue. Let us know if you have any idea on how to improve your experience.

**Closed by jsilvestre** 2015-05-05 12:09 UTC
Labels: 1 - Todo, bug
