### ISSUE TITLE
Duplicated name folder and no error ?

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-files#426] opened 2016-06-07 08:46 UTC
Context: I was trying to stream few (10) music files using cozic. So I've copied the mp3 in a directory, then ran cozic sync. It's been running for nearly 2hours now, I guess it's dead but I can't find a way to stop the process (there is no cancel button)...

And now, I can see in the 'files' app that I have *2* directories names 'Cozic' in the root. I'm not sure exactly why, but I guess this is not wanted.

The first is empty, the second I'm not sure : opening it simply displays the 'loading' animation and nothing more.

**Comment by dkm** [comment] 2016-06-07 09:42
FYI, the 'files' app is still trying to list the content of the second 'Cozic' directory.

**Comment by clochix** [comment] 2016-06-08 14:53
Thanks for this report, looks like there are several bugs:
 - the sync failing. I guess there's been an error, but this application has no server component, so I don't have the logs of the errors happening inside the browser;
 - a display error inside Files (there's a JS error that prevent the content of the folder from being displayed, I'm trying to fix it).

**Comment by clochix** [comment] 2016-06-08 15:54
Seems like the issue is on cozy-music side.

You had one track in the old Cozic application, so, when Cozy-music starts, it create a Cozic folder inside Files and import there your tracks. Unfortunately, there was an error creating this folder, so it is corrupted inside database, and Files is unable to display its content. I just manually deleted this wrong folders.

Could you try to open the developer console of your browser, reload cozy-music and tell us if you see any javascript error?

**Comment by dkm** [comment] 2016-06-09 08:44
Before starting Coxy-music, when logging in cozy : 
```
unreachable code after return statement vendor.js:26952:12384
WARNING: Missing translation for key: "downloader description" vendor.js:27291:42
WARNING: Missing translation for key: "thelounge description" vendor.js:27291:42
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. vendor.js:3571:28
```
When starting cozt-music : 
```
TypeError: t.binary is undefined
 app.38fe8539e2a5b2c5f4ed.js:30:12216
```
Note that it is still trying to sync with files.

**Comment by clochix** [comment] 2016-06-09 09:59
Thanks @dkm, I found the error: there are no file attached to your track in Cozic. I just applied a quickfix on your server, could you try it?

**Comment by dkm** [comment] 2016-06-09 11:08
I reopened the app only to see it blocked again, but after the sync : "Retrieving all new and deleted files..." :)

There is no more duplicated folder, and I can list it (empty).

**Comment by clochix** [comment] 2016-06-10 15:30
Looks like there's an issue while importing content from Cozic. But it's not a file related issue, so I suggest to close this issue and open another one in cozy-labs/cozy-music repository.

**Comment by jsilvestre** [comment] 2016-08-18 16:30
I opened the issue, so I close this one (https://github.com/cozy-labs/cozy-music/issues/104).

**Closed by jsilvestre** 2016-08-18 16:30 UTC
Labels: bug
