### ISSUE TITLE
Improve file deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-files#317] opened 2015-07-27 12:31 UTC
Some users ( @nitot ) are complaining that's it's not easy to discover how to delete a file. Maybe could we add a delete icon when hovering a file.

**Comment by nitot** [comment] 2015-07-27 13:43
Absolutely. Thank you @clochix for opening this issue. I had someone on the phone explaining me how ot do this yet I had a hard time finding the button. :-/

**Comment by jsilvestre** [comment] 2015-07-27 14:32
duplicate of https://github.com/cozy/cozy-files/issues/210

**Closed** 2016-08-23 14:38 UTC
Labels: duplicate, enhancement
