### ISSUE TITLE
Performing bulk action "move all" leaks memory

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#174] opened 2014-09-12 06:18 UTC
When performing the bulk action "move all" repeatedly, the server's memory slowly increases (1MB~ for 100 files moved).

**Comment by frankrousseau** [comment] 2015-01-29 09:29
Is the memory never freed?

**Comment by jsilvestre** [comment] 2015-01-29 09:30
I don't know, I never pushed the investigation further, I'm super bad at that.

**Comment by frankrousseau** [comment] 2015-03-01 13:52
The issue is old and noone complained about this. Let's close it.

**Closed by frankrousseau** 2015-03-01 13:52 UTC
Labels: bug, P2
