### ISSUE TITLE
Accessing shared files results to a 404

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#259] opened 2015-04-01 10:29 UTC
A user reported that it couldn't access its shared files.

I couldn't reproduce.

**Comment by vaz-ar** [comment] 2015-04-01 10:41
I have the same problem, I uploaded files and I'm unable to share them

**Comment by poupotte** [comment] 2015-05-06 07:19
I don't arrive to reproduce it. @vaz-ar, do you still have this behavior ? 
It happens for specific folders or files ?

@jsilvestre, do you have more information for this issue ?

**Comment by vaz-ar** [comment] 2015-05-06 13:45
I just tried, it seems that I cannot reproduce anymore.

**Comment by poupotte** [comment] 2015-05-06 13:52
Thanks @vaz-ar .
I propose to close this issue and re-open it if someone has this bug. @clochix ?

**Comment by clochix** [comment] 2015-05-06 15:59
Ok, let's close, thanks to both of you ☺

**Closed by clochix** 2015-05-06 15:59 UTC
Labels: 1 - Todo, bug
