### ISSUE TITLE
duplicate directories and empty string directories

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-files#272] opened 2015-05-04 08:33 UTC
Trying out cozy files. The UI has some bugs : 

* [x] I click on create new folder, try to start typing the name since it's selected, that doesn't work, so I clic on the field and type the name and press enter
* [x] if you click multiple times on create folder then type a folder name, the folder is created twice
* [x] if you click on create folder, give it an existing folder name that is duplicated it creates a "empty" string folder with no "last update" information.

![screenshot from 2015-05-04 10 27 56](https://cloud.githubusercontent.com/assets/108437/7450742/c9e28c50-f248-11e4-95d3-fc9e08599bef.png)

* after that I can't create a folder, the create folder button does not do anything. Renaming the empty string folder get the button to work again.

**Comment by jsilvestre** [comment] 2015-05-04 08:34
Thank you very much for your report, we'll take care of it!

**Comment by clochix** [comment] 2015-05-15 14:51
Thanks @jsilvestre, everything looks fine ☺

**Comment by jsilvestre** [comment] 2015-05-18 07:04
@arthurlutz could you please update your application and tell us if those problems have been fixed?

**Comment by arthurlutz** [comment] 2015-05-18 08:38
@jsilvestre the empty string bug is gone. 

the duplicate folder is still there on creation, when refreshing the page on a single folder is there. 

Another bug : you can create a folder with an empty string, but then you can't go into it (but you can delete it).

**Comment by jsilvestre** [comment] 2015-05-18 08:54
Can you clear your cache and try again please? It looks like you don't run the actual latest version. Sorry for the inconvenience.

**Comment by arthurlutz** [comment] 2015-05-18 09:12
Can you be more precise on "clear your cache" ? Hard refresh ? cache server side ?

**Comment by jsilvestre** [comment] 2015-05-18 09:17
Sorry, I meant a hard refresh yes, the browser cache.

**Comment by arthurlutz** [comment] 2015-05-18 09:39
I did.

**Comment by clochix** [comment] 2015-05-18 10:13
I created a new ticket (#282) for the empty folder name problem.

I'm unable to reproduce your duplicate folder bug ☹ Which browser are you using ?

**Comment by arthurlutz** [comment] 2015-05-18 10:41
Firefox 37.0.2 (ubuntu)

**Comment by jsilvestre** [comment] 2015-05-22 07:57
Hello @arthurlutz,
We are very sorry, but nobody on the team have been able to reproduce the issue (folder appears twice when created) :-/ Would you mind trying in another browser?

**Comment by clochix** [comment] 2015-08-11 11:05
Hi @arthurlutz,
Are you still facing this issue ?

**Comment by arthurlogilab** [comment] 2015-08-11 12:50
@clochix seems ok

**Comment by clochix** [comment] 2015-08-11 15:30
Thanks, closing it :-)

**Closed by clochix** 2015-08-11 15:30 UTC
Labels: bug
